class DataAlreadyExistsError(Exception):
    """Raises when trying to create additional data on unique existent"""
